FLOSSIES - All genes - Cross referencing
Packages used
```{r}
library(tidyverse)
library(here)
library(janitor)
library(visdat)
library(skimr)
library(rstatix)
library(dplyr)
library(knitr)
library('corrr')
library(ggcorrplot)
library("FactoMineR")
library(factoextra)
```

Data Loading - FLOSSIES
```{r}
atm_floss <- clean_names(read.csv(here("data/Justine/flossies/ATM.csv")))
bard1_floss <- clean_names(read.csv(here("data/Justine/flossies/BARD1.csv")))
brca1_floss <- clean_names(read.csv(here("data/Justine/flossies/BRCA1.csv")))
brca2_floss <- clean_names(read.csv(here("data/Justine/flossies/BRCA2.csv")))
chek2_floss <- clean_names(read.csv(here("data/Justine/flossies/CHEK2.csv")))
palb2_floss <- clean_names(read.csv(here("data/Justine/flossies/PALB2.csv")))
rad51c_floss <- clean_names(read.csv(here("data/Justine/flossies/RAD51C.csv")))
rad51d_floss <- clean_names(read.csv(here("data/Justine/flossies/RAD51D.csv")))
tp53_floss <- clean_names(read.csv(here("data/Justine/flossies/TP53.csv")))

flossies <- full_join(atm_floss, bard1_floss) %>% full_join(brca1_floss) %>% full_join(brca2_floss) %>% full_join(chek2_floss) %>% full_join(palb2_floss) %>% full_join(rad51c_floss) %>% full_join(rad51d_floss) %>% full_join(tp53_floss) %>%  mutate(alternate = case_when(alternate == "" ~ "-", T ~ alternate),
                    reference = case_when(reference == "" ~ "-", T ~ reference)) %>% unite(dbnsfp, chrom, position, reference, alternate, sep = " ")
```

Flossies analysed
```{r}
gnomad_count %>% 
  unite(dbnsfp, chromosome, position, reference, alternate, sep = " ") %>% 
  inner_join(flossies, by = "dbnsfp") %>% 
  group_by(gene) %>% 
  count(Population) %>% 
  mutate(percent = (round((n/sum(n))*100,2))) %>% 
  ggplot(aes(x= gene, y= percent, fill= Population)) + 
  geom_col(alpha= 0.7, colour = "black") +
  scale_fill_manual(values = c("African_american" = "#800080", 
                               "Latino_admixed_american" = "darkgreen", 
                               "Non_finnish_european" = "gray", 
                               "East_asian" = "navy",
                               "South_asian" = "darkred"))

gnomad_count %>% 
  unite(dbnsfp, chromosome, position, reference, alternate, sep = " ") %>% 
  inner_join(flossies, by = "dbnsfp") %>% 
  select(gene, dbnsfp, Population, clin_var_clinical_significance) %>% 
  filter(clin_var_clinical_significance=="Blank")
#Reportedly all of FLOSSIES data is from women without cancer above the age of 70. But according to gnomAD, most of them are uncertain and not benign.
#Check where 9 blank comes from
```
